version: '3.1'
services:
  http:
    image: nginx:1.17.6-alpine
    volumes:
      - ./backend:/app
      - ./config/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    environment:
      NGINX_HOST: localhost
      NGINX_PORT: 80
      TZ: UTC
    depends_on:
      - php
  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./.data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      TZ: UTC
  php:
    image: php
    depends_on:
      - db
      - redis
    links:
      - db
    restart: unless-stopped
    environment:
      REDIS_LOCK: redis:6379
      ENV: development
      PHP_IDE_CONFIG: serverName=localhost
      TZ: Europe/Rome
    build:
      context: .
      dockerfile: ./config/docker/php/Dockerfile
    volumes:
      - ./backend:/app
      - ./config/docker/php/custom.ini:/etc/php7/conf.d/03_custom.ini
  redis:
    image: redis
    restart: unless-stopped
    environment:
      TZ: Europe/Rome